Repository KinsonDigital/Carbonate, pull requests merged in 2022-12, with the labels that each got.

#2 🚧Initial Implementation
  .config/dotnet-tools.json
  .editorconfig
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .nuke/parameters.json
  .run/CarbonateTesting.run.xml
  .vscode/settings.json
  CONTRIBUTING.md
  Carbonate.sln
  Carbonate.sln.DotSettings
  Carbonate/Carbonate.csproj
  Carbonate/ExtensionMethods.cs
  Carbonate/IMessage.cs
  Carbonate/IReactable.cs
  Carbonate/IReactor.cs
  Carbonate/JsonMessage.cs
  Carbonate/Reactable.cs
  Carbonate/Reactor.cs
  Carbonate/ReactorUnsubscriber.cs
  Carbonate/Services/ISerializer.cs
  Carbonate/Services/JsonSerializer.cs
  Carbonate/carbonate-logo.ico
  Carbonate/stylecop.json
  Documentation/Branching.md
  Documentation/Images/carbonate-logo-dark-mode.png
  Documentation/Images/carbonate-logo-light-mode.png
  Documentation/Images/twitter-logo-16x16.svg
  Documentation/ReleaseNotes/Preview-Release-Notes-TEMPLATE.md
  Documentation/ReleaseNotes/Production-Release-Notes-TEMPLATE.md
  LICENSE.md
  README.md
  Testing/.editorconfig
  Testing/CarbonateTesting/CarbonateTesting.csproj
  Testing/CarbonateTesting/DataSerializer.cs
  Testing/CarbonateTesting/IMyObject.cs
  Testing/CarbonateTesting/MyObject.cs
  Testing/CarbonateTesting/ObjectMessage.cs
  Testing/CarbonateTesting/Program.cs
  Testing/CarbonateTesting/SunData.cs
  Testing/CarbonateTesting/stylecop.json
  Testing/CarbonateTests/CarbonateTests.csproj
  Testing/CarbonateTests/Helpers/TestData.cs
  Testing/CarbonateTests/JsonMessageTests.cs
  Testing/CarbonateTests/ReactableTests.cs
  Testing/CarbonateTests/ReactorTests.cs
  Testing/CarbonateTests/ReactorUnsubscriberTests.cs
  Testing/CarbonateTests/stylecop.json
Labels: high priority, preview

#5 🚀Preview Release
  .config/dotnet-tools.json
  .editorconfig
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  .nuke/parameters.json
  .run/CarbonateTesting.run.xml
  .vscode/release-notes.code-snippets
  .vscode/settings.json
  CONTRIBUTING.md
  Carbonate.sln
  Carbonate.sln.DotSettings
  Carbonate/Carbonate.csproj
  Carbonate/ExtensionMethods.cs
  Carbonate/IMessage.cs
  Carbonate/IReactable.cs
  Carbonate/IReactor.cs
  Carbonate/JsonMessage.cs
  Carbonate/Reactable.cs
  Carbonate/Reactor.cs
  Carbonate/ReactorUnsubscriber.cs
  Carbonate/Services/ISerializer.cs
  Carbonate/Services/JsonSerializer.cs
  Carbonate/carbonate-logo.ico
  Carbonate/stylecop.json
  Documentation/Branching.md
  Documentation/Images/carbonate-logo-dark-mode.png
  Documentation/Images/carbonate-logo-light-mode.png
  Documentation/Images/twitter-logo-16x16.svg
  Documentation/ReleaseNotes/Preview-Release-Notes-TEMPLATE.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.1.md
  Documentation/ReleaseNotes/Production-Release-Notes-TEMPLATE.md
  LICENSE.md
  README.md
  Testing/.editorconfig
  Testing/CarbonateTesting/CarbonateTesting.csproj
  Testing/CarbonateTesting/DataSerializer.cs
  Testing/CarbonateTesting/IMyObject.cs
  Testing/CarbonateTesting/MyObject.cs
  Testing/CarbonateTesting/ObjectMessage.cs
  Testing/CarbonateTesting/Program.cs
  Testing/CarbonateTesting/SunData.cs
  Testing/CarbonateTesting/stylecop.json
  Testing/CarbonateTests/CarbonateTests.csproj
  Testing/CarbonateTests/Helpers/TestData.cs
  Testing/CarbonateTests/JsonMessageTests.cs
  Testing/CarbonateTests/ReactableTests.cs
  Testing/CarbonateTests/ReactorTests.cs
  Testing/CarbonateTests/ReactorUnsubscriberTests.cs
  Testing/CarbonateTests/stylecop.json
Labels: 🚀Preview Release

#8 Check for grammar/spelling issues in documentation
  Carbonate/IReactable.cs
  Carbonate/IReactor.cs
  Carbonate/JsonMessage.cs
  Carbonate/Reactor.cs
  Carbonate/Services/JsonSerializer.cs
Labels: good first issue, medium priority, preview, 📝documentation/product

#11 🚧Update CICD to latest version
  .config/dotnet-tools.json
Labels: high priority, preview, workflow

#12 🚧Add parameterless constructor to Reactable
  Carbonate.sln.DotSettings
  Carbonate/Reactable.cs
  Testing/CarbonateTesting/Program.cs
  Testing/CarbonateTests/JsonMessageTests.cs
Labels: high priority, preview, ✨new feature

#13 🚧Change nuget package icon
  Carbonate/Carbonate.csproj
Labels: high priority, preview, 📝documentation/product

#15 🚀Preview Release
  .config/dotnet-tools.json
  .vscode/settings.json
  Carbonate.sln.DotSettings
  Carbonate/Carbonate.csproj
  Carbonate/Reactable.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
  Testing/CarbonateTesting/Program.cs
  Testing/CarbonateTests/JsonMessageTests.cs
Labels: 🚀Preview Release

#17 🚧Fix bug with message deserialization
  Carbonate/JsonMessage.cs
  Testing/CarbonateTests/JsonMessageTests.cs
Labels: high priority, preview, 🐛bug

#19 🚀Preview Release
  Carbonate/Carbonate.csproj
  Carbonate/JsonMessage.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.3.md
  Testing/CarbonateTests/JsonMessageTests.cs
Labels: 🚀Preview Release

#21 🚧Fix bug with unsubscriptions
  Carbonate.sln
  Carbonate.sln.DotSettings
  Carbonate/Reactable.cs
  Testing/CarbonateIntegrationTests/CarbonateIntegrationTests.csproj
  Testing/CarbonateIntegrationTests/IntegrationTests.cs
  Testing/CarbonateIntegrationTests/SampleData.cs
  Testing/CarbonateIntegrationTests/stylecop.json
  Testing/CarbonateTesting/CarbonateTesting.csproj
  Testing/CarbonateTesting/DataSerializer.cs
  Testing/CarbonateTesting/IMyObject.cs
  Testing/CarbonateTesting/MyObject.cs
  Testing/CarbonateTesting/ObjectMessage.cs
  Testing/CarbonateTesting/Program.cs
  Testing/CarbonateTesting/SunData.cs
Labels: high priority, preview, 🐛bug

#23 🚀Preview Release
  .vscode/settings.json
  Carbonate.sln
  Carbonate.sln.DotSettings
  Carbonate/Carbonate.csproj
  Carbonate/Reactable.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  Testing/CarbonateIntegrationTests/CarbonateIntegrationTests.csproj
  Testing/CarbonateIntegrationTests/IntegrationTests.cs
  Testing/CarbonateIntegrationTests/SampleData.cs
  Testing/CarbonateIntegrationTests/stylecop.json
  Testing/CarbonateTesting/CarbonateTesting.csproj
  Testing/CarbonateTesting/DataSerializer.cs
  Testing/CarbonateTesting/IMyObject.cs
  Testing/CarbonateTesting/MyObject.cs
  Testing/CarbonateTesting/ObjectMessage.cs
  Testing/CarbonateTesting/Program.cs
  Testing/CarbonateTesting/SunData.cs
Labels: 🚀Preview Release

#25 🚧Change Reactable class API
  Carbonate/IReactable.cs
  Carbonate/Reactable.cs
  Testing/CarbonateIntegrationTests/IntegrationTests.cs
  Testing/CarbonateTests/ReactableTests.cs
Labels: high priority, preview, 🧨breaking changes

#27 🚀Preview Release
  Carbonate/Carbonate.csproj
  Carbonate/IReactable.cs
  Carbonate/Reactable.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md
  Testing/CarbonateIntegrationTests/IntegrationTests.cs
  Testing/CarbonateTests/ReactableTests.cs
Labels: 🚀Preview Release

#30 🚧Add push notification
  Carbonate/IMessage.cs
  Carbonate/IReactable.cs
  Carbonate/IReactor.cs
  Carbonate/Reactable.cs
  Carbonate/Reactor.cs
  Testing/CarbonateIntegrationTests/IntegrationTests.cs
  Testing/CarbonateTests/ReactableTests.cs
  Testing/CarbonateTests/ReactorTests.cs
Labels: high priority, preview, ✨new feature

#32 🚀Preview Release
  Carbonate/Carbonate.csproj
  Carbonate/IMessage.cs
  Carbonate/IReactable.cs
  Carbonate/IReactor.cs
  Carbonate/Reactable.cs
  Carbonate/Reactor.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.6.md
  README.md
  Testing/CarbonateIntegrationTests/IntegrationTests.cs
  Testing/CarbonateTests/ReactableTests.cs
  Testing/CarbonateTests/ReactorTests.cs
Labels: 🚀Preview Release

#34 🚧Fix bug with unsubscribe from all
  Carbonate/Reactable.cs
  Testing/CarbonateTests/ReactableTests.cs
Labels: high priority, preview, 🐛bug

#36 🚀Preview Release
  Carbonate/Carbonate.csproj
  Carbonate/Reactable.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.7.md
  Testing/CarbonateTests/ReactableTests.cs
Labels: 🚀Preview Release

#38 🚧Update checkout action
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
Labels: good first issue, preview, workflow

#42 🚧Fix unsubscription bug
  Carbonate/JsonMessage.cs
  Carbonate/Reactable.cs
  Carbonate/Services/ISerializerService.cs
  Carbonate/Services/JsonSerializerService.cs
  Testing/CarbonateTests/JsonMessageTests.cs
  Testing/CarbonateTests/ReactableTests.cs
Labels: high priority, preview, 🐛bug

#43 🚧Fix issue with Reactable disposal process
  Carbonate/Reactable.cs
  Testing/CarbonateTests/ReactableTests.cs
Labels: high priority, preview, 🐛bug

#44 🚧Add event names
  Carbonate/IReactor.cs
  Carbonate/Reactor.cs
  Testing/CarbonateTests/ReactableTests.cs
  Testing/CarbonateTests/ReactorTests.cs
Labels: high priority, preview, ✨new feature

#46 🚀Preview Release
  .github/workflows/build-pr-status-check.yml
  .github/workflows/feature-pr-status-check.yml
  .github/workflows/hotfix-pr-status-check.yml
  .github/workflows/prev-feature-pr-status-check.yml
  .github/workflows/prev-release-pr-status-check.yml
  .github/workflows/prev-release.yml
  .github/workflows/prod-release-pr-status-check.yml
  .github/workflows/prod-release.yml
  .github/workflows/unit-test-pr-status-check.yml
  Carbonate/Carbonate.csproj
  Carbonate/IReactor.cs
  Carbonate/JsonMessage.cs
  Carbonate/Reactable.cs
  Carbonate/Reactor.cs
  Carbonate/Services/ISerializerService.cs
  Carbonate/Services/JsonSerializerService.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.8.md
  Testing/CarbonateTests/JsonMessageTests.cs
  Testing/CarbonateTests/ReactableTests.cs
  Testing/CarbonateTests/ReactorTests.cs
Labels: 🚀Preview Release
