Repository KinsonDigital/Carbonate, pull requests merged in 2023-08, with the labels that each got.

#131 🚧Adjust release workflow input
  .github/workflows/release.yml
  .vscode/settings.json
Labels: low priority, preview, ♻️cicd

#129 🚧Improve readme
  README.md
Labels: low priority, 📝documentation/product

#137 🚧Lock version of MOQ
  .github/workflows/sync-bot.yml
  README.md
  Testing/CarbonateTests/CarbonateTests.csproj
Labels: 📦dependency update, high priority

#144 🚧Adjust workflow triggers
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/sonar-scan-pr-status-check.yml
  .github/workflows/sync-bot.yml
  .github/workflows/sync-issue-to-pr.yml
  .github/workflows/sync-pr-to-issue.yml
  .github/workflows/sync-status-check.yml
  .github/workflows/test-status-check.yml
Labels: high priority, preview, ♻️cicd
